Make languagePolicy configurable in TestScript
microsoft/botbuilder-dotnet pull request #4794
Opened 2020-10-14 06:49 UTC by Danieladu

Original issue: https://github.com/microsoft/botbuilder-dotnet/issues/4143
First PR: https://github.com/microsoft/botbuilder-dotnet/pull/4784

## Description
The first PR make language policy in MultiLanguageRecognizer align with the policy in UseLanguagePolicy,
this PR make the LanguagePolicy configurable in TestScript

## Specific Changes
- Add `LanguagePolicy` property in TestScript
- Remove the parameter assignment of languagePolicy in TestScript

2020-10-20 16:49 UTC, chrimc62 commented on tests/tests.schema
> +                  "minItems": 1,
If you are going to regenerate this file you need to make sure you are running the latest bf dialog:merge by doing bf plugins:install @microsoft/bf-dialog@next

2020-10-20 16:50 UTC, chrimc62 requested changes
:clock1:

2020-10-20 16:52 UTC, chrimc62 approved these changes
:shipit:

2020-10-21 01:23 UTC, Danieladu commented
@microsoft/bb-dotnet could you take a look?

2020-10-21 03:21 UTC, mrivera-ms approved these changes

2020-10-21 03:21 UTC, merged