Update orchestrator-core to 4.11.0-rc2.preview
microsoft/botbuilder-dotnet pull request #4962
Opened 2020-11-12 19:37 UTC by taicchoumsft

## Description
Update the orchestrator-core native dependencies to pick up a linux-related fix (native icu dependencies cannot be found due to naming error), all other OSes unaffected.

## Specific Changes
  - Update `Microsoft.BotFramework.Orchestrator` version to `4.11.0-rc2.preview`

2020-11-12 19:54 UTC, tsuwandy approved these changes

2020-11-12 22:33 UTC, daveta requested changes
Tai, 
(Chatting with Tien) Maybe we should update this to:
`4.12.0-daily*` 
In preparation for R12 - so we're up to date on dailies..

2020-11-17 22:30 UTC, daveta approved these changes

2020-11-18 17:51 UTC, johnataylor commented
We are concerned about the hardcoded package version as this is inconsistent with the rest of the product build. Can you explain why this is necessary?

2020-11-18 18:25 UTC, mrivera-ms commented
@daveta, @tsuwandy , could you please look at the comment added above by @johnataylor ? Thank you.

2020-11-18 18:55 UTC, tsuwandy commented
@mrivera-ms, @johnataylor, @daveta is building a new package with 4.11.* tag...

2020-11-19 20:55 UTC, mrivera-ms commented
@tsuwandy, is this still needed or can we close it. FYI @johnataylor , @daveta .

2020-11-19 21:17 UTC, tsuwandy commented
@mrivera-ms, Microsoft.BotFramework.Orchestrator 4.11.2.daily* package was deployed and I updated the reference.

2020-12-03 23:40 UTC, mrivera-ms approved these changes

2020-12-03 23:40 UTC, merged