Fix FileTranscriptLogger
microsoft/botbuilder-dotnet pull request #5047
Opened 2020-12-12 16:47 UTC by peterbozso

## Description

The `FileTranscriptLogger` has a bug when it's being used in a bot that is being tested locally from the Bot Framework Emulator.

The problem is that the logger is trying to create a transcript file with the following name format: `<conversationId>.transcript`. But when you are talking to the from the Emulator, the conversation ID is set by the Emulator to strings like this: `8b6e9a80-3c94-11eb-83c4-83172d04969b|livechat`.

I have no idea about Linux/Mac (and a bit lazy right now to check :)), but I am 100% sure that on Windows, the `|` character is not valid character in a filename (it's before the `livechat` part in the above example), thus the `FileTranscriptLogger` will fail to log any activities to the filesystem. Worst of all, this does it silently, leaving almost zero traces of the issue in the bot's logs.

This PR intends to fix both of these issues: the usage of incorrect filenames and the lack of logging.

## Specific Changes
  - Add error logging when we fail to log an Activty to the filesystem.
  - Make sure we use valid filenames for saving the transcript file, regardless of host OS.

2020-12-14 14:29 UTC, gabog requested changes
Thanks @peterbozso, this looks like a great fix, would you be able to add a test to https://github.com/microsoft/botbuilder-dotnet/blob/main/tests/Microsoft.Bot.Builder.Tests/FileTranscriptTests.cs so we can take this PR?

Thanks!

2021-02-03 21:07 UTC, tomlm approved these changes
:shipit:

2021-02-18 14:29 UTC, peterbozso commented
@gabog is this good to be merged? :)

2021-03-29 12:49 UTC, gabog commented
/azp run  BotBuilder-DotNet-CI-PR-yaml

2021-03-29 13:08 UTC, gabog commented
/azp run BotBuilder-DotNet-CI-PR-(MacLinux)-yaml

2021-03-29 13:21 UTC, gabog approved these changes
Looks good @peterbozso, thanks for your contributions and apologies that it took so long to get this merged but we had other higher priority issues to address in the previous release and this one didn't make it.

2021-03-29 13:21 UTC, merged

2021-03-29 14:22 UTC, peterbozso commented
@gabog no issues, thanks for the feedback! 🙂