Add top level lazy load on LanguageGeneratorManager
microsoft/botbuilder-dotnet pull request #6123
Opened 2022-01-14 01:31 UTC by Danieladu

Fixes #6116

## Description
Make  LanguageGenerators Lazy in LanguageGeneratorManager to reduce the cost of loading.

2022-01-21 19:51 UTC, EricDahlvang commented on libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs
> +                Console.WriteLine($"Found result of type {result.GetType().Name} for {cacheKey} in cache");
Remove Console.WriteLine

2022-01-21 19:52 UTC, EricDahlvang approved these changes

2022-01-24 17:01 UTC, gabog commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguageGeneratorExtensions.cs
> +            bool lazyMode = false)
@Danieladu this code seems to be only used in tests and it is not clear to my why the tests fail if I try with lazyMode == true.

Lazy should be a performance optimization and it should work in both cases, lazy == false should load resources on demand and lazy == true should load them upfront, regardless, it should work in both cases unless we are doing something wrong.

2022-01-24 21:34 UTC, gabog requested changes
Waiting for review with @Danieladu and @boydc2014

2022-01-25 03:25 UTC, gabog commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs
> +        internal void LazyLoad()
Consider combining this method with internal void LazyLoad(IEnumerable<Resource> resources) in a single metho

2022-01-26 07:25 UTC, gabog commented on libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguageGeneratorExtensions.cs
> +            bool lazyMode = false)
This parameter has been removed.

2022-01-26 16:49 UTC, carlosscastro approved these changes

2022-01-26 17:18 UTC, gabog approved these changes

2022-01-26 17:57 UTC, merged